# action.yml
name: 'Changelog Action'
description: 'Prints a changelog message'
inputs:
  message:
    description: 'The message to print'
    required: true
runs:
  using: 'node12'
  main: 'src/main.js'
