name: 'Changelog Action'
description: 'Generate and display changelog in pull request'
inputs:
  pr-number:
    description: 'Pull request number'
    required: true
  github-token:
    description: 'GitHub token'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
